
input_file: prompts.txt
output_dir: output
commit_message_tag: "~4LLM"
prompt_extension: .llm_prompt
target_extension: .py
branch_name: complete-code
commit_message: "Completed code using OpenAI LLM"

max_tokens: 1024

model_name: gpt-3.5-turbo

completion_options:
  temperature: 0.8
  max_tokens: 100
