name: Draw Owl

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME: "llm_autocomplete"
  COMMIT_MESSAGE: "LLM autocomplete"
  TRIGGER_WORD: 4LLM

# https://github.com/actions/runner/issues/662
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: early
        name: Branch check
        run: |
          status="skip"
          if [[ ! "${{ github.event.head_commit.message }}" =~ $TRIGGER_WORD ]]
          then
            status="execute"
          fi

          echo "status=$status" >> $GITHUB_OUTPUT



  complete_code:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'execute'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message
      run: |
        if [[ ! "${{ github.event.head_commit.message }}" =~ $TRIGGER_WORD ]]; then
          echo "Commit message does not contain trigger word. Skipping job."
          exit 0
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run draw_owl.py
      run: python draw_owl.py
        
    - name: Create branch and commit
      run: |
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m $COMMIT_MESSAGE
        git push origin $BRANCH_NAME
