name: Draw Owl

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME: lllm_autocomplete
  COMMIT_MESSAGE: LLM autocomplete
  TRIGGER_WORD: 4LLM

jobs:
  complete_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run draw_owl.py
      run: |
        if echo "${{ github.event.head_commit.message }}" | grep -iq $TRIGGER_WORD; then
          python draw_owl.py
        else
          echo "Skipping draw_owl.py as commit message does not contain trigger word" $TRIGGER_WORD
        fi

    - name: Create branch and commit
      run: |
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m $COMMIT_MESSAGE
        git push origin $BRANCH_NAME
