name: Draw Owl

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME
  COMMIT_MESSAGE

jobs:
  complete_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run draw_owl.py
      run: python draw_owl.py

    - name: Get config output
      id: config_output
      run: echo "::set-output name=config::$(cat config.yaml)"

    - name: Create branch and commit
      run: |
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m $COMMIT_MESSAGE
        git push origin $BRANCH_NAME
