name: Draw Owl

on:
  push:
    branches:
      - main

jobs:
  complete_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run complete_code.py
      run: python complete_code.py

    - name: Get config output
      id: config_output
      run: echo "::set-output name=config::$(cat config.yaml)"

    - name: Create branch and commit
      run: |
        git checkout -b ${{ fromJson(steps.config_output.outputs.config).branch_name }}
        git add .
        git commit -m "${{ fromJson(steps.config_output.outputs.config).commit_message }}"
        git push origin ${{ fromJson(steps.config_output.outputs.config).branch_name }}
